repos:
  - repo: git@git.zhlh6.cn:PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
  - repo: git@git.zhlh6.cn:psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: git@git.zhlh6.cn:myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [ '--in-place', '--remove-all-unused-imports', '--remove-unused-variable', '--ignore-init-module-imports' ]


