[project]
name = "recruitment"
version = "0.1.0"
description = ""
authors = [
    {name = "lp1506947671",email = "xiaopawnye@163.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django (>=5.2.4,<6.0.0)"
]

[tool.poetry]
packages = [{include = "recruitment", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
